# -*- coding: utf-8 -*-
"""Streamlit Contact List

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bzw37Y_MsIZcNzrv7vqCpVrCVESgNW6V
"""

# Install Streamlit if not already installed in the Colab environment
try:
    import streamlit as st
except ImportError:
    !pip install streamlit
    import streamlit as st # Import again as st after installation

import re
import requests
import pandas as pd
import os
import socket
import urllib.parse
import time
import sys
import io # For in-memory file operations

# Streamlit and xlsxwriter should be installed via requirements.txt in deployed environments.
# The subprocess.check_call blocks for installation are removed for deployment, but included
# here with !pip for Colab execution.

st.set_page_config(layout="wide")
st.title("Google Places Contact Scraper")

# Install xlsxwriter if not already installed
try:
    import xlsxwriter
except ImportError:
    !pip install xlsxwriter
    import xlsxwriter


# =========================
# CONFIGURATION (Streamlit Inputs)
# =========================
st.header("Configuration")

api_key = st.text_input("Enter your Google Cloud API Key (Places API, Geocoding API)", type="password")

target_city_state_input = st.text_area("Enter target cities and states (one per line, e.g., 'Panama City, FL')", value="Panama City, FL\nNew York, NY")
TARGET_CITY_STATE_LIST = [city.strip() for city in target_city_state_input.split('\n') if city.strip()]

SEARCH_RADIUS_MILES = st.slider("Search Radius in Miles", min_value=1, max_value=100, value=50)
SEARCH_RADIUS_METERS = SEARCH_RADIUS_MILES * 1609.34

BUSINESS_TYPES_DEFAULT = ['property manager', 'realtor', 'apartment']
business_types_input = st.text_area("Enter business types to search for (one per line)", value="\n".join(BUSINESS_TYPES_DEFAULT))
BUSINESS_TYPES = [bt.strip() for bt in business_types_input.split('\n') if bt.strip()]

TYPE_MAP = {
    "property manager": "PM",
    "realtor": "R",
    "apartment": "APT",
}

# =========================
# Helper: Google API Call Functions
# =========================
@st.cache_data(ttl=3600) # Cache coordinates for an hour
def get_coordinates(address, api_key_arg):
    base_url = "https://maps.googleapis.com/maps/api/geocode/json"
    params = {
        "address": address,
        "key": api_key_arg
    }
    try:
        response = requests.get(base_url, params=params, timeout=10)
        response.raise_for_status()
        data = response.json()

        if data["status"] == "OK" and data["results"]:
            location = data["results"][0]["geometry"]["location"]
            return location["lat"], location["lng"]
        else:
            st.warning(f"Error getting coordinates for {address}: {data['status']}")
            return None, None
    except requests.exceptions.RequestException as e:
        st.error(f"Network error for {address}: {e}")
        return None, None

@st.cache_data(ttl=3600) # Cache search results for an hour
def search_places(query, location, radius, api_key_arg):
    all_places = []
    next_page_token = None
    progress_bar = st.progress(0)
    progress_text = st.empty()
    page_count = 0

    while True:
        url = (
            "https://maps.googleapis.com/maps/api/place/textsearch/json"
            f"?query={query}&location={location}&radius={radius}&key={api_key_arg}"
        )
        if next_page_token:
            url += f"&pagetoken={next_page_token}"

        try:
            r = requests.get(url, timeout=30)
            r.raise_for_status()
            data = r.json()

            all_places.extend(data.get("results", []))
            next_page_token = data.get("next_page_token")

            page_count += 1
            progress_text.text(f"Searching for '{query}': Collected {len(all_places)} places (Page {page_count})")
            # Update progress bar (can't know total pages, so just increment a bit)
            progress_bar.progress(min(page_count * 10, 100)) # Arbitrary increment for visual feedback

            if not next_page_token:
                break

            time.sleep(2) # Required delay between paginated requests
        except requests.exceptions.RequestException as e:
            st.error(f"Network error during place search for '{query}': {e}")
            break
    progress_bar.empty()
    progress_text.empty()
    return all_places

@st.cache_data(ttl=3600) # Cache place details for an hour
def place_details(place_id, api_key_arg):
    url = (
        "https://maps.googleapis.com/maps/api/place/details/json"
        f"?place_id={place_id}&key={api_key_arg}"
    )
    try:
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return r.json().get("result", {})
    except requests.exceptions.RequestException as e:
        st.error(f"Network error getting details for place_id {place_id}: {e}")
        return {}

def infer_type_from_query(query_text: str) -> str:
    q = query_text.lower()
    for k, v in TYPE_MAP.items():
        if k in q:
            return v
    return ""

# =========================
# RUN SCRAPING PROCESS
# =========================
def run_scraper(api_key, target_cities, business_types, search_radius_meters):
    if not api_key:
        st.error("Please enter your Google API Key to start the search.")
        return pd.DataFrame()
    if not target_cities:
        st.error("Please enter at least one target city.")
        return pd.DataFrame()
    if not business_types:
        st.error("Please enter at least one business type.")
        return pd.DataFrame()

    all_raw_results = []
    deduplicated_results_map = {}

    overall_progress_text = st.empty()
    overall_progress_bar = st.progress(0);

    for i, current_target_city_state in enumerate(target_cities):
        overall_progress_text.text(f"Processing city: {current_target_city_state}")
        overall_progress_bar.progress((i + 1) / len(target_cities))

        current_lat, current_lng = get_coordinates(current_target_city_state, api_key)

        if current_lat is None or current_lng is None:
            st.warning(f"Could not get coordinates for {current_target_city_state}. Skipping this city.")
            continue

        st.info(f"Searching {current_target_city_state} (Lat: {current_lat}, Lng: {current_lng})")

        for business_type in business_types:
            query = f"{current_target_city_state} {business_type}"
            st.info(f"Performing search for: {query}")

            short_type = infer_type_from_query(business_type)

            places = search_places(
                query=query,
                location=f"{current_lat},{current_lng}",
                radius=search_radius_meters,
                api_key=api_key
            )

            if not places:
                st.info(f"No places found for '{query}'.")
                continue

            details_bar = st.progress(0)
            details_text = st.empty()
            for j, p in enumerate(places):
                place_id = p.get("place_id")
                if not place_id:
                    continue

                details = place_details(place_id, api_key)

                address = details.get("formatted_address", "")
                city = ""
                state = ""
                zip_code = ""

                address_components = details.get("address_components", [])
                for component in address_components:
                    types = component.get("types", [])
                    if "locality" in types:
                        city = component.get("long_name")
                    elif "administrative_area_level_1" in types:
                        state = component.get("short_name")
                    elif "postal_code" in types:
                        zip_code = component.get("long_name")

                website_url = details.get("website")

                row = {
                    "Type": short_type,
                    "Source": "Google",
                    "Organization": details.get("name"),
                    "Address": address,
                    "City": city,
                    "State": state,
                    "Zip": zip_code,
                    "Phone": details.get("formatted_phone_number"),
                    "Notes": "",
                    "Contact Name": "",
                    "Title": "",
                    "Website": website_url,
                    "Email": "",
                    "Rating": details.get("rating"),
                    "Query Source": query,
                    "Searched City": current_target_city_state,
                }

                all_raw_results.append(row)

                details_bar.progress((j + 1) / len(places))
                details_text.text(f"Getting details for {details.get('name', 'a place')} ({j+1}/{len(places)} in this search)")
            details_bar.empty()
            details_text.empty()

    overall_progress_bar.empty()
    overall_progress_text.empty()

    st.success(f"Collected raw data for {len(all_raw_results)} entries. Now deduplicating...")

    for row in all_raw_results:
        org = row.get('Organization')
        addr = row.get('Address')
        unique_key = (org, addr)

        if unique_key in deduplicated_results_map:
            existing_entry = deduplicated_results_map[unique_key]
            current_types = set(existing_entry['Type'].split('/'))
            new_type = row.get('Type')
            if new_type and new_type not in current_types:
                current_types.add(new_type)
            sorted_types = sorted(list(current_types))
            existing_entry['Type'] = '/'.join(sorted_types)
            deduplicated_results_map[unique_key] = existing_entry
        else:
            deduplicated_results_map[unique_key] = row.copy()

    results = list(deduplicated_results_map.values())
    st.success(f"Collected details for {len(results)} deduplicated places.")

    df = pd.DataFrame(results)
    return df


def check_dns_resolution(url):
    if pd.isna(url) or not url:
        return False
    try:
        if not urllib.parse.urlparse(url).scheme:
            url = "http://" + url
        hostname = urllib.parse.urlparse(url).netloc
        if not hostname:
            return False
        socket.gethostbyname(hostname)
        return True
    except (socket.gaierror, AttributeError, ValueError):
        return False


if st.button("Run Scraper"): # Main button to trigger the process
    with st.spinner("Starting data collection..."):
        # Run the scraper and get the initial DataFrame
        initial_df = run_scraper(api_key, TARGET_CITY_STATE_LIST, BUSINESS_TYPES, SEARCH_RADIUS_METERS)

    if not initial_df.empty:
        st.subheader("Processing and Prioritizing Data...")

        with st.spinner("Checking DNS resolution for websites..."):
            initial_df['DNS_Resolves'] = initial_df['Website'].apply(check_dns_resolution)
            st.success("DNS resolution check completed.")

        # Prioritize and sort
        filtered_df = initial_df.sort_values(by=['Rating', 'Organization'], ascending=[False, True]).copy()

        st.subheader("Prioritized Contacts (First 10 Rows)")
        st.dataframe(filtered_df.head(10))

        # Generate a descriptive name for the output file
        output_city_segment = "_and_".join([city.split(',')[0].strip().replace(' ', '_') for city in TARGET_CITY_STATE_LIST])
        new_output_file_name = f"Prioritized_{output_city_segment}_Contacts.xlsx"

        # Define desired column order
        desired_cols = [
            "Type","Source","Organization","Address","City","State","Zip","Phone",
            "Notes","Contact Name","Title","Website","Email","Rating","Query Source", "DNS_Resolves", "Searched City"
        ]

        # Reindex the filtered DataFrame to match the desired column order
        filtered_df = filtered_df.reindex(columns=desired_cols)

        # Export to Excel in-memory
        output = io.BytesIO()
        writer = pd.ExcelWriter(output, engine='xlsxwriter')
        filtered_df.to_excel(writer, sheet_name='Prioritized Contacts', index=False)

        # Access the XlsxWriter workbook and worksheet objects
        workbook  = writer.book
        worksheet = writer.sheets['Prioritized Contacts']

        # Add a format for 'True' values (light green fill).
        green_format = workbook.add_format({'bg_color': '#C6EFCE'})
        # Add a format for 'False' values (light red fill).
        red_format = workbook.add_format({'bg_color': '#FFC7CE'})

        # Get the column index for 'DNS_Resolves'
        try:
            dns_resolves_col_idx = filtered_df.columns.get_loc('DNS_Resolves')
            # Helper function to convert column index to Excel column name
            def get_excel_column_name(col_idx_val):
                name = ''
                while col_idx_val >= 0:
                    name = chr(col_idx_val % 26 + ord('A')) + name
                    col_idx_val = col_idx_val // 26 - 1
                return name

            excel_col_name = get_excel_column_name(dns_resolves_col_idx)
            cell_range = f'{excel_col_name}2:{excel_col_name}{len(filtered_df) + 1}'

            # Apply conditional formatting
            worksheet.conditional_format(cell_range, {'type': 'cell', 'criteria': '==', 'value': True, 'format': green_format})
            worksheet.conditional_format(cell_range, {'type': 'cell', 'criteria': '==', 'value': False, 'format': red_format})
        except KeyError:
            st.warning("Could not apply conditional formatting: 'DNS_Resolves' column not found.")

        writer.close()
        output.seek(0) # Go to the beginning of the stream

        st.subheader("Download Results")
        st.download_button(
            label="Download Excel file",
            data=output,
            file_name=new_output_file_name,
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        )
        st.success(f"Generated {len(filtered_df)} prioritized contacts for download.")
    else:
        st.warning("No data was collected. Please check your API key, cities, and business types.")